const config = require('./twit-config')
const twit = require('twit')
const fetch = require('node-fetch')
const _ = require('lodash')

const T = new twit(config)


const prefijos = [
  'Aero',
  'An',
  'Ambi',
  'Anfi',
  'Ante',
  'Anti',
  'Arz',
  'Auto',
  'bi',
  'bis',
  'biz',
  'bien',
  'co',
  'com',
  'con',
  'contra',
  'cuasi',
  'de',
  'des',
  'epi',
  'equi',
  'ex',
  'extra',
  'hemi',
  'hetero',
  'hiper',
  'hyper',
  'hipo',
  'homo',
  'in',
  'infra',
  'inter',
  'entre',
  'intra',
  'iso',
  'macro',
  'maxi',
  'mega',
  'micro',
  'mini',
  'mono',
  'multi',
  'neo',
  'peri',
  'pluri',
  'poli',
  'pos',
  'post',
  'pre',
  'pro',
  're',
  'retro',
  'semi',
  'pseudo',
  'sub',
  'so',
  'super',
  'sobre',
  'supra',
  'trans',
  'tras',
  'contra',
  'ultra',
  'neuro',
  'uni',
  'psico',
  'vi',
  'vice',
  'viz',
  'meta',
  'video',
  'post',
  'socio',
  'ultra',
  'pre',
  'homo',
  'cyber'
]

const doctrinas = [
  'aristotelismo',
  'ascetismo',
  'confucianismo',
  'deísmo',
  'empirismo',
  'escepticismo filosófico',
  'estructuralismo',
  'fenomenología',
  'pitagorismo',
  'hermenéutica',
  'inteligencia',
  'holismo',
  'kantianismo',
  'erotismo',
  'materialismo',
  'personalismo',
  'platonismo',
  'poscolonialismo',
  'racionalismo',
  'accidentalismo',
  'agatonismo',
  'ajivika',
  'anticiencia',
  'antroposofía',
  'artefactualismo',
  'atomismo',
  'averroísmo',
  'terrorismo',
  'cartesianismo',
  'cientificismo',
  'conceptualismo',
  'marxismo',
  'cosmismo ruso',
  'creacionismo',
  'criticismo',
  'determinismo comsológico',
  'dinamismo',
  'dadaísmo',
  'doble verdad',
  'dogmatismo',
  'estética francesa',
  'estoicismo',
  'excepcionalismo humano',
  'falsacionismo',
  'fenomenalismo',
  'formalismo',
  'naturalismo',
  'fundamentalismo',
  'escolástica',
  'nominalismo',
  'hedonismo',
  'hegelianismo',
  'hilozoísmo',
  'humanismo',
  'ocasionalismo',
  'optimismo',
  'oscurantismo',
  'dinamismo',
  'conciencia',
  'idealismo alemán',
  'ignosticismo',
  'indeterminismo',
  'instrumentalismo',
  'intelectualismo socrático',
  'intuicionismo ético',
  'intuitivismo',
  'irracionalismo',
  'pampsiquismo',
  'panteísmo ateo',
  'pensamiento comunitario',
  'perdurantismo',
  'perspectivismo',
  'pesimismo',
  'platonismo',
  'platonismo matemático',
  'positivismo',
  'purismo',
  'utilitarismo',
  'expresionismo',
  'romanticismo',
  'vanguardismo',
  'esoterismo',
  'cogito',
  'taoísmo',
  'solipsismo',
  'idealismo',
  'virtual',
  'corporal',
  'informático',
  'sintáctico',
  'artificial'
]

const adjetivos = [
  'geométrico',
  'marxista',
  'biológico',
  'humanista',
  'binario',
  'digital',
  'cibernético',
  'anarquista',
  'especista',
  'religioso',
  'comunista',
  'psicodèlico',
  'histórico',
  'socialista',
  'capitalista',
  'fordista',
  'animalista',
  'fluctuante',
  'circundante',
  'evolutivo',
  'existencialista',
  'primitivo',
  'hedonista',
  'aceleracionista',
  'porno',
  'queretano',
  'sexual',
  'freudiano',
  'jungiano',
  'infinito',
  'cuántico',
  'japonés',
  'mecánico',
  'romántico',
  'contemporáneo',
  'futurista',
  'estético',
  'textual',
  'punk',
  'fantasmagórico',
  'neuronal',
  'onírico',
  'musical',
  'vitalista',
  'estructuralista',
  'fatalista',
  'electrónico',
  'moderno',
  'postmoderno',
  'universal',
  'monista',
  'politeísta',
  'democrático',
  'liberal',
  'fascista',
  'totalitario',
  'multidimensional',
  'lacánico',
  'soviético',
  'globalista',
  'corporativo',
  'feudalista',
  'monárquico',
  'intelectual',
  'gótico',
  'revolucionario',
  'burgués',
  'psicoanalítico',
  'metafísico',
  'lógico',
  'trascendental',
  'idealista',
  'cosmológico',
  'dialéctico',
  'analítico',
  'continental',
  'empírico',
  'budista',
  'nacionalista',
  'antagónico',
  'chamanista',
  'conservador',
  'satánico',
  'occidental',
  'oriental',
  'marciano',
  'mágico',
  'clásico',
  'antiguo',
  'anacrónico',
  'atemporal',
  'oral',
  'situacionista',
  'vanguardista',
  'ancestral',
  'político',
  'tecnológico',
  'surreal'
]

setInterval(() => {
  let nPrefijo = prefijos[Math.floor(Math.random() * prefijos.length)]
  let nDoctrinas = doctrinas[Math.floor(Math.random() * doctrinas.length)]
  let nAdjetivos = adjetivos[Math.floor(Math.random() * adjetivos.length)]
  console.log(nPrefijo + nDoctrinas + ' ' + nAdjetivos)
  T.post('statuses/update', {
    status: `${_.capitalize(nPrefijo)}${nDoctrinas} ${nAdjetivos}`
  }, tweeted)
}, 60000)


function tweeted(err, data, response) {
  console.log('Se mandó el tuit.');
}